apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: strimzi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Homelab strimzi Cluster
  sourceRepos:
    - "https://github.com/trajanoreuter/kubernetes-homelab"
    - "quay.io/strimzi-helm/strimzi-kafka-operator"
  destinations:
    - namespace: "*"
      name: in-cluster
    - namespace: strimzi
      name: in-cluster
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceBlacklist:
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: false
  roles:
    - name: strimzi
      description: Sync privileges for strimzi
      policies:
        - p, proj:strimzi:strimzi, applications, *, strimzi/*, allow
