apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kong
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Homelab kong Cluster
  sourceRepos:
    - 'https://github.com/trajanoreuter/kubernetes-homelab'
  destinations:
    - namespace: kong
      name: in-cluster
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false
  roles:
    - name: kong
      description: Sync privileges for kong
      policies:
      - p, proj:kong:kong, applications, *, kong/*, allow
