apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Homelab vault Cluster
  sourceRepos:
    - 'https://github.com/trajanoreuter/kubernetes-homelab'
  destinations:
    - namespace: vault
      name: in-cluster
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false
  roles:
    - name: vault
      description: Sync privileges for vault
      policies:
      - p, proj:vault:vault, applications, *, vault/*, allow
