{{- if .Values.initialJob.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-chart.fullname" . }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app: {{ include "api-chart.fullname" . }}
    job: {{ .Values.application.name }}
    {{- include "api-chart.labels" . | nindent 4 }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  created_at: {{ now }}
{{- end }}

{{- if .Values.configMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-chart.fullname" . }}-configmap
  annotations:
    argocd.argoproj.io/hook: PreSync
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
  {{- include "api-chart.labels" . | nindent 4 }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- range .Values.configMap }}
  {{ .name }}: |
    {{- with .values }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- end -}}
{{- end -}}