apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "api-chart.serviceAccountName" . }}
  labels:
    {{- include "api-chart.labels" . | nindent 4 }}
    {{- with .Values.labels }}
          {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}