apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store-vault
  namespace: external-secrets
spec:
  controller: default
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "development/secrets"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "external-secrets"
          key: "token"
