apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Homelab grafana Cluster
  sourceRepos:
    - 'https://github.com/trajanoreuter/kubernetes-homelab'
  destinations:
    - namespace: grafana
      name: in-cluster
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false
  roles:
    - name: grafana
      description: Sync privileges for grafana
      policies:
      - p, proj:grafana:grafana, applications, *, grafana/*, allow
