apiVersion: v2
name: homelab-vault
description: A Helm chart for vault
type: application
version: 1
appVersion: "1.15.2"
dependencies:
- name: vault
  version: 0.28.0
  repository: https://helm.releases.hashicorp.com
