apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homelab
  namespace: postgres
spec:
  instances: 1
  bootstrap:
    initdb:
      database: homelab
      owner: homelab
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: vault-init
            key: vault-init.sql
      secret:
        name: homelab-postgres-secret
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: false
