apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Homelab prometheus Cluster
  sourceRepos:
    - 'https://github.com/trajanoreuter/kubernetes-homelab'
  destinations:
    - namespace: prometheus
      name: in-cluster
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false
  roles:
    - name: prometheus
      description: Sync privileges for prometheus
      policies:
      - p, proj:prometheus:prometheus, applications, *, prometheus/*, allow
